extends: airbnb
plugins:
  - babel
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
rules:
  # 下面两条规则在 babel-eslint 下有 bug
  indent: 0
  template-curly-spacing: 0
  #
  semi:
    - 2
    - never
  no-nested-ternary: 0
  max-len:
    - 2
    - 140
  no-shadow: 0
  no-case-declarations: 0
  no-param-reassign: 0
  consistent-return: 0
  default-case: 0
  no-return-assign:
    - 2
    - except-parens
  jsx-quotes:
    - 2
    - prefer-single
  import/first: 0
  import/prefer-default-export: 0
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  react/sort-comp: 0
  react/no-did-mount-set-state: 0
  jsx-a11y/click-events-have-key-events: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/anchor-is-valid: 0
  jsx-a11y/anchor-has-content: 0